### PR TITLE
Ijr add assertthat sec nov23

### PR DESCRIPTION
**Pull request by ian-rickard**
Hi @pbbgss, I've added a section on `assertthat` to `rmd_files/content.Rmd`. I don't know if that's the correct file, but would you please review what I've done? We can move it if necessary.

Do we want to remove Example 5 from earlier in the script?

Also, although I've developed this, if you're happy with presenting it, there's no reason why it shouldn't be moved to another part of the class  - i.e. part that I don't deliver -  if it makes sense to put it there. The more I think about it, the more it seems to me that the very end of the class is not the best place.

Point of interest:

It looks like there's some kind of hierarchy in the assertion statements, or in the messages that are returned to the user. In the following example, `is.numeric()` is asserted/reported before/in preference to `>`. This looks like helpful behaviour, to cause focus on (1) the fundamental failure of type, rather than (2) the failure of the other test to even execute as a result of (1), but I wasn't aware of it before. I'd be interested to know what this is called, if you happen to know.

```
pythagoras <- function(a, b) {
  
  assertthat::assert_that(a > 0, msg = "a must be > 0")
  
  c <- sqrt(a^2 + b^2)
  
  return(c)
}

> pythagoras("two", 3)
Error in a^2 : non-numeric argument to binary operator
```

```
pythagoras <- function(a, b) {
  
  assertthat::assert_that(a > 0, msg = "this test is chronologically first")
  assertthat::assert_that(is.numeric(a), msg = "this test is chronologically second")
  
  c <- sqrt(a^2 + b^2)
  
  return(c)
}

> pythagoras("two", 3)
Error: this test is chronologically second
```

Followup - looks like it's the prioritisation is done on the basis of whether an assertion executed, rather than any characteristics of the assertions. Replacing the first assertion with one that can be executed causes it to be reported.

```
pythagoras <- function(a, b) {
  
  assertthat::assert_that(a == "three", msg = "this test is chronologically first")
  assertthat::assert_that(is.character(a), msg = "this test is chronologically second")
  
  c <- sqrt(a^2 + b^2)
  
  return(c)
}

> pythagoras("two", 3)
Error: this test is chronologically first
```

### CODE REVIEW

**Comment by pbbgss** [comment]
@ian-rickard On your point of interest

`Error in a^2 : non-numeric argument to binary operator` is coming from `"two"^2` not the assertion (i.e. the string passed to `a`). 

The assertion `assertthat::assert_that(a > 0, msg = "a must be > 0")` is passing because of the behaviour of `>`.  When evaluated `"two" > 0` returns `TRUE`.

From the help for `>`: "If the two arguments are atomic vectors of different types, one is coerced to the type of the other, the (decreasing) order of precedence being character, complex, numeric, integer, logical and raw."

(I haven't looked into the methods for why `"two" > "0"` is `TRUE` however!

**Comment by pbbgss** [comment]
@ian-rickard Yes it looks like the majority of the material is in `rmd_files/content.Rmd` and it then knitted into the various other media. Not sure I like having the course content duplicated in the README - would a README more like the one in the [R charting repo](https://github.com/moj-analytical-services/ggplotTraining#r-charting) be more useful?

**Comment by pbbgss** [comment]
I think that throughout the training course we are recommending people follow  the tidyverse style guide. (If we are not recommending a single style guide we probably should be!) One of the things it covers in the functions section is [the use of `return()`](https://style.tidyverse.org/functions.html#return). This is something that is not followed in this course at the moment but is on my "to-do" list to fix. Please could you update the code in this PR? For example:
```R
pythagoras <- function(a, b) {
  
  assertthat::assert_that(a > 0, msg = "a must be > 0")
  
  c <- sqrt(a^2 + b^2)
  
  return(c)
}
```
could be written as:
```R
pythagoras <- function(a, b) {
  
  assertthat::assert_that(a > 0, msg = "a must be > 0")
  
  sqrt(a^2 + b^2)
  
}

**Comment by pbbgss** [comment]
Thanks for putting this section together! In general it looks great - I'll have a look in more detail at the content/ where it might best fit in the rest of the training once I have gone though and made some changes there (I hope tomorrow but if not, the first half of next week).

**Comment by ian-rickard** [comment]
> I think that throughout the training course we are recommending people follow the tidyverse style guide. (If we are not recommending a single style guide we probably should be!) One of the things it covers in the functions section is [the use of `return()`](https://style.tidyverse.org/functions.html#return). This is something that is not followed in this course at the moment but is on my "to-do" list to fix. Please could you update the code in this PR? For example:
> 
> ```r
> pythagoras <- function(a, b) {
>   
>   assertthat::assert_that(a > 0, msg = "a must be > 0")
>   
>   c <- sqrt(a^2 + b^2)
>   
>   return(c)
> }
> ```
> 
> could be written as:
> 
> ```r
> pythagoras <- function(a, b) {
>   
>   assertthat::assert_that(a > 0, msg = "a must be > 0")
>   
>   sqrt(a^2 + b^2)
>   
> }
> ```

Thanks - I remember now you mentioning this.

Yes, I have revised in line with this (I hope). Slightly differently to your suggestion - I wanted to an additional step so that I could have product testing in the final exercise, so I used a concatenated the value into a reporting string. Let me know if that doesn't suit.

**Comment by ian-rickard** [comment]
> @ian-rickard On your point of interest
> 
> `Error in a^2 : non-numeric argument to binary operator` is coming from `"two"^2` not the assertion (i.e. the string passed to `a`).
> 
> The assertion `assertthat::assert_that(a > 0, msg = "a must be > 0")` is passing because of the behaviour of `>`. When evaluated `"two" > 0` returns `TRUE`.
> 
> From the help for `>`: "If the two arguments are atomic vectors of different types, one is coerced to the type of the other, the (decreasing) order of precedence being character, complex, numeric, integer, logical and raw."
> 
> (I haven't looked into the methods for why `"two" > "0"` is `TRUE` however!

Thanks for that!

re. the final bit, I looked it up and apparently it's to do with 'lexicographical' order of characters

**Comment by pbbgss** [comment]
> re. the final bit, I looked it up and apparently it's to do with 'lexicographical' order of characters

Interesting - do you have a link for that?

Would it be worth including an `assert_that(is.numeric(a))` to show how you can catch incorrect types/classes? And possibly also a check that a value is supplied to the arguments? e.g. something like:

```R
pythagoras <- function(a, b) {

  assertthat::assert_that(!missing(a), msg = "you must supply argument 'a'")
  assertthat::assert_that(is.numeric(a))
  assertthat::assert_that(a > 0, msg = "a must be > 0")
  
  sqrt(a^2 + b^2)
  
}

pythagoras("1",2 )

pythagoras(b = 2)
```
Asserting that the argument is not missing might mean we need to talk about the difference between "missing" , `NA` and `NULL` which might be a bit advance for an introduction to functions though?

**Comment by ian-rickard** [comment]
> > re. the final bit, I looked it up and apparently it's to do with 'lexicographical' order of characters
> 
> Interesting - do you have a link for that?
> 
> Would it be worth including an `assert_that(is.numeric(a))` to show how you can catch incorrect types/classes? And possibly also a check that a value is supplied to the arguments? e.g. something like:
> 
> ```r
> pythagoras <- function(a, b) {
> 
>   assertthat::assert_that(!missing(a), msg = "you must supply argument 'a'")
>   assertthat::assert_that(is.numeric(a))
>   assertthat::assert_that(a > 0, msg = "a must be > 0")
>   
>   sqrt(a^2 + b^2)
>   
> }
> 
> pythagoras("1", 2)
> 
> pythagoras(b = 2)
> ```
> 
> Asserting that the argument is not missing might mean we need to talk about the difference between "missing" , `NA` and `NULL` which might be a bit advance for an introduction to functions though?

No link, it's unverified from chatgpt.

Yes, happy to add the other stuff. Will revisit next week.

**Review by pbbgss — APPROVED** [review]
Thanks for putting this together; it flows nicely and gives a solid introduction.

For the exercises should we say we are making a new function called `pythagorus_rounded()` based on the original? At the moment adding the "is whole number" assertion to the output feels a little strange from a maths perspective. Would it also be worth adding a hint to round `c` before returning it to exercise 7.3?

**Comment by ian-rickard** [comment]
> Thanks for putting this together; it flows nicely and gives a solid introduction.
> 
> For the exercises should we say we are making a new function called `pythagorus_rounded()` based on the original? At the moment adding the "is whole number" assertion to the output feels a little strange from a maths perspective. Would it also be worth adding a hint to round `c` before returning it to exercise 7.3?

thanks - ok, done!

**Pull request merged**
